// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --local > src/types/database.types.ts

// Placeholder types for development
export type Database = {
  public: {
    Tables: {
      profiles: any;
      intents: any;
      gallery_photos: any;
      verification_requests: any;
      connections: any;
      connection_members: any;
      messages: any;
      reports: any;
      admin_users: any;
    };
    Enums: {
      profile_type: 'single' | 'couple';
      verification_status: 'unverified' | 'pending' | 'verified' | 'rejected' | 'banned';
      verification_request_status: 'pending' | 'approved' | 'rejected';
      photo_status: 'approved' | 'pending_review' | 'rejected';
      connection_type: 'one_to_one' | 'two_to_one' | 'one_to_two' | 'group';
      connection_status: 'pending' | 'matched' | 'blocked';
      member_role: 'single' | 'couple';
    };
  };
};

// Custom types
export type Profile = Database['public']['Tables']['profiles'];
export type Intent = Database['public']['Tables']['intents'];
export type GalleryPhoto = Database['public']['Tables']['gallery_photos'];
export type VerificationRequest = Database['public']['Tables']['verification_requests'];
export type Connection = Database['public']['Tables']['connections'];
export type Message = Database['public']['Tables']['messages'];
