// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --local > src/types/database.types.ts

// Placeholder types for development
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          profile_type: 'single' | 'couple';
          display_name: string | null;
          couple_name: string | null;
          bio: string | null;
          avatar_url: string | null;
          avatar_locked: boolean | null;
          verification_status: 'unverified' | 'pending' | 'verified' | 'rejected' | 'banned';
          verified_at: string | null;
          strikes: number | null;
          active_intent_id: string | null;
          accepted_dynamics: any | null; // JSON
          terms_accepted_at: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id: string;
          profile_type?: 'single' | 'couple';
          display_name?: string | null;
          couple_name?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          verification_status?: 'unverified' | 'pending' | 'verified' | 'rejected' | 'banned';
          terms_accepted_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          profile_type?: 'single' | 'couple';
          display_name?: string | null;
          couple_name?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          verification_status?: 'unverified' | 'pending' | 'verified' | 'rejected' | 'banned';
          terms_accepted_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey";
            columns: ["id"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      admin_users: {
        Row: {
          user_id: string;
          email: string;
          granted_by: string | null;
          created_at: string | null;
        };
        Insert: {
          user_id: string;
          email: string;
          granted_by?: string | null;
        };
        Update: {
          user_id?: string;
          email?: string;
          granted_by?: string | null;
        };
      };
      intents: any;
      gallery_photos: any;
      verification_requests: any;
      connections: any;
      connection_members: any;
      messages: any;
      reports: any;
    };
    Enums: {
      profile_type: 'single' | 'couple';
      verification_status: 'unverified' | 'pending' | 'verified' | 'rejected' | 'banned';
      verification_request_status: 'pending' | 'approved' | 'rejected';
      photo_status: 'approved' | 'pending_review' | 'rejected';
      connection_type: 'one_to_one' | 'two_to_one' | 'one_to_two' | 'group';
      connection_status: 'pending' | 'matched' | 'blocked';
      member_role: 'single' | 'couple';
    };
  };
};

// Custom types
export type Profile = Database['public']['Tables']['profiles'];
export type Intent = Database['public']['Tables']['intents'];
export type GalleryPhoto = Database['public']['Tables']['gallery_photos'];
export type VerificationRequest = Database['public']['Tables']['verification_requests'];
export type Connection = Database['public']['Tables']['connections'];
export type Message = Database['public']['Tables']['messages'];
