create table if not exists public.profile_media (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  media_type text not null,
  storage_path text not null,
  moderation_status text not null default 'pending',
  moderation_labels jsonb,
  moderation_score numeric,
  moderated_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists profile_media_user_id_idx on public.profile_media(user_id);

insert into storage.buckets (id, name, public)
values ('profile_media', 'profile_media', false)
on conflict (id) do nothing;
