alter table public.profiles
  add column if not exists show_comments boolean default true;

update public.profiles
  set show_comments = true
  where show_comments is null;

create table if not exists public.follows (
  id bigint generated by default as identity primary key,
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (follower_id, following_id)
);

create index if not exists follows_follower_idx on public.follows(follower_id);
create index if not exists follows_following_idx on public.follows(following_id);
