alter table public.profiles
  add column if not exists dm_privacy text not null default 'matches';

alter table public.profiles
  drop constraint if exists profiles_dm_privacy_check;

alter table public.profiles
  add constraint profiles_dm_privacy_check
  check (dm_privacy in ('all', 'matches'));

create table if not exists public.dm_consent_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  target_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (requester_id, target_id),
  check (requester_id <> target_id),
  check (status in ('pending', 'accepted', 'rejected', 'canceled'))
);

alter table public.dm_consent_requests enable row level security;

drop policy if exists "dm_consent_select" on public.dm_consent_requests;
drop policy if exists "dm_consent_insert" on public.dm_consent_requests;
drop policy if exists "dm_consent_update" on public.dm_consent_requests;

create policy "dm_consent_select"
on public.dm_consent_requests
for select
to authenticated
using (auth.uid() = requester_id or auth.uid() = target_id);

create policy "dm_consent_insert"
on public.dm_consent_requests
for insert
to authenticated
with check (auth.uid() = requester_id);

create policy "dm_consent_update"
on public.dm_consent_requests
for update
to authenticated
using (auth.uid() = requester_id or auth.uid() = target_id)
with check (auth.uid() = requester_id or auth.uid() = target_id);
